
name = "swiftrootbus"
main = "workers-site/index.js"   # Entry point for your worker
type = "javascript"              # or "modules" depending on Astro setup

account_id = "6c225d7b23f6ee9825b9ae4ca57afd1b"
workers_dev = true
compatibility_flags = ["nodejs_compat"]  # required for node built-ins like 'fs' or 'child_process'
